// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhvwkhjebooeoyncgoag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpodndraGplYm9vZW95bmNnb2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTc2OTUsImV4cCI6MjA3MTc3MzY5NX0.jncSdyy6Ks8ruBi_FbhBxcwGraq7VLWN89g42VNEHnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});